### ISSUE TITLE
undefined method `ensure_key_dir_exists'

### ISSUE THREAD

**Issue by jschrama** [tehmaze/hiera-eyaml-secretbox#1]
With hiera-eyaml 2.1.0, the `eyaml` command throws the following error:

```
[hiera-eyaml-core] Loaded config from /etc/eyaml/config.yaml
[hiera-eyaml-core] undefined method `ensure_key_dir_exists' for Hiera::Backend::Eyaml::Utils:Class
[hiera-eyaml-core] /opt/ruby2.0/lib/vendor_ruby/2.0.0/hiera/backend/eyaml/encryptors/secretbox.rb:74:in `create_keys'
                   /opt/ruby2.0/lib/vendor_ruby/2.0.0/hiera/backend/eyaml/subcommands/createkeys.rb:20:in `execute'
                   /opt/ruby2.0/lib/vendor_ruby/2.0.0/hiera/backend/eyaml/CLI.rb:46:in `execute'
                   /usr/local/bin/eyaml:21:in `<main>'
```

This is related to a change in the latest release of hiera-eyaml, specifically [this commit](https://github.com/voxpupuli/hiera-eyaml/commit/705eadd91d1807055c20b949ae6fcb94b4533045).

**Comment by jschrama** [comment]
I have made a pull request with a fix for this issue: https://github.com/tehmaze/hiera-eyaml-secretbox/pull/2
